dist: trusty
language: python
python:
- '2.7'
sudo: false
services:
- redis-server
addons:
  postgresql: '9.5'
  apt:
      packages:
          - ghostscript
env:
    global:
        secure: "PA5dSDNTC5YNZyujT2hkKBJvqPzZRuFC+/d/8JXxSteaJLJcryDF0Lf3PZLT8VJI/Pvb7lziLUd33vPzStRq7ZOOQxQ007POJSqjcBwD5Tdg2bM19j1d/wzWqyXGqnaEI1QZOZIsTa3ZW8xi13/REJXzlywGIUQHJKrE6NdvVSqLElYu+F9FXk7BRwCTztQdyiB/C3tf4cGmBzHKSLBJjVSRvS+vmX7P34mWFaW5/kL09mICuX19wstntwsXVXxVvCFm/XtAmMcRvfsecgnnXjzxtdT4c7iFH7BBsanqXsVrwZWJVIFB8V3hkPKsRSxFU5VIYv++pW8vTCG7ieBJOiQLnNEG5GcA18gHW11ioDPPJfTz6h8RhWhD41e4EvvgUfJO2SPzzbJ+DUuspg91m3VCo7tQ1TxaOdApzsiIhk0LVwP8YzPidvDIdavRxSVp3ZERa3+OMjut+n5XUsO+53v1AtcvU5THcrLHgvBuVhzhatT+yeM0nFb/V1RsvXVn3YfN5BNxk5kxWEzLNKxmGzCAo1lleAXfSrUDaP6FB3RQk/xcyQhSJPRhg6X3r9A15Zy1s4ojfZcHsn7x9pUVGXAn6lpaSGJSxyB0SMUo3exkBKaBOdEKpa3eVfZvyu/dADAbFnJsgR2o6v21nexVx/qt76PpzM1FKxt9ofC05fc="
        secure: "n6ZKH6ZwudnUWBaCDsjatjzW5Pmc6mt1XvreZQR/CfrC69QCqB/KXXP4EKfpEod0+0p7EV7vxeOsPD5XvkitQt9dvihM7Q/aF7wAVpRdvNmXGKojQOxKc83MvDVHBdux7MKEBO9ROWe73wHpMoRqccbs9LUSU6msBxNAPf9ypmmqvNe1TYVk2fwk5CQ6oaMgQaKbiJL+1n0dZwSNsvVr2LMrMI2y8l/j0snUtcrEp+t2VnhNgc3w034BKJV5GEU+cklf//QZY9Ee3GhubLbn4FwBUeLMFgEOCv/wUw4XRDOVSe6karHQr1Nm6m5hlsSpQGvluU2qUM2vHnMH1cVBfyYOX/+uyCmhQCvbhExRQ0MCkcFND0Fli2oV6fNCTJPK0zOndY9YWek4H0HIe1KscVaMRrknGQqP/dvzbTi6RcIfZ8b2mZX8qVU2YMIvbyj1U0F4r2KYDoJgBzGyoj9mt6zATpHLEywNQ8a4awXvObvLik4GEjFUhesGQ8O4VOmHzoXNRkU9XAVM2zc97Dnhf5yB5QiN8lo6tiA5cJmh50/CV+w/zgwKHNIzs1KNWLrGh0LRAVyIpH12rNQNZdq8XCSKZO0qQ2jOmirtxaSPKbDEkv+I6GKyW+6WH0WDil97fFd+PUglP5msi7BFe3ns9RPd8D30yl4u/gVhT5ZxOww="
        secure: "uru4Ga12MPDtRCizuNQXh8LMWJXpclf+unYV235/hEAiiEaubOy8AnHKIPHqV45FEqu0ASJaN2LxcxCydh1MLyn+ECjRE1ZzwUk8qZiEJkRPeNOEXJ4VaWO7Epd1+9j53883P0Xp/zjLfeY9FzR1Ews2iGmaw7lMujXnzJhWgaG6QO7D41oZVXYHMqBi6kV2MzxBReIDzEOAvc6lN+vS8WRKMmILaQFAtlK+vg99U/faOMYfHqH8LTYM7sJ5V8jgSI730PMN6CD7kGiWR3Vi8kc4sV/U8rS9TgpVmYN4RzBZ8OfxxOobXMmVmuD8Lrfu2pCa/c5O3EKVC8DzSb9etwjoDGQpC1lZ29pmJRtTb6QFZnwE8S2W3r7buk2/mRPsVPEyj2qqJEhEwYX7Zqg7rEF/tyKIBTqTOXPeznK8cV729gE7EJjFrhgPAhan6kJdpASY6meYOsIQ3WLS5j8888tX6XvzEAg1R3x2+tCgD+cUoc8UBGJWy2m4+KHorab5duYYv+UFZzh1MPc41Y0HYnUvmGYo1szQVNG+c1f7ECTe+p7TWsmhcUKIiTRqfWIfK4vjGLMczwfEhUOsBW1seL1wcJmjvEP8AxA3vdk5/5qVlH5DAUMH/xCNA7nxnjD7CkTiTRRgkJx6hx1uk8jwOvyU+WG9XPVDB2TZXj1fVcM="
before_install:
- redis-server --version
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda3/bin:$PATH
- conda update --yes conda
install:
  - df -h
  - sudo service postgresql stop
  - mkdir /tmp/why
  - sudo sed -i 's/^data_directory/#data_directory/' /etc/postgresql/9.5/main/postgresql.conf
  - echo "data_directory='/tmp/why95/'" | sudo tee --append /etc/postgresql/9.5/main/postgresql.conf
  - sudo sed -i 's/^data_directory/#data_directory/' /etc/postgresql/9.2/main/postgresql.conf
  - echo "data_directory='/tmp/why92/'" | sudo tee --append /etc/postgresql/9.2/main/postgresql.conf
  - sudo pg_createcluster --datadir=/tmp/why95 9.5 testdata
  - sudo pg_createcluster --datadir=/tmp/why92 9.2 testdata
  - sudo service postgresql start
  - sudo psql -U postgres -c "create database travis"
  - sudo psql -U postgres -c "show data_directory;"
  - travis_retry conda create --yes -n labadmin python=2.7 pip
  - source activate labadmin
  - pip install -U pip
  - pip install -U click natsort coverage coveralls
  - travis_retry pip install -U .[test]
script:
  - git clone https://github.com/biocore/american-gut-web.git ~/build/biocore/american-gut-web
  - cd /home/travis/build/biocore/american-gut-web
  - export AG_CONFIG=`pwd`/ag_config.txt.example
  - export PYTHONPATH=/home/travis/build/biocore/american-gut-web:$PYTHONPATH
  - export VIOSCREEN_USERNAME=$VIOSCREEN_USERNAME
  - export VIOSCREEN_PASSWORD=$VIOSCREEN_PASSWORD
  - export VIOSCREEN_REGISTRATION=$VIOSCREEN_REGISTRATION
  - df -h
  - ./scripts/ag make test
  - export PYTHONPATH=
  - $PYTHONPATH
  - cd $TRAVIS_BUILD_DIR
  - cp $TRAVIS_BUILD_DIR/knimin/config.txt.example $TRAVIS_BUILD_DIR/knimin/config.txt
  - nosetests --verbose --with-doctest --with-coverage --cover-package=knimin
  - flake8 --ignore E722 knimin setup.py scripts
after_success:
- coveralls
