dist: trusty
language: python
python:
- '2.7'
sudo: false
services:
- redis-server
addons:
  postgresql: '9.5'
  apt:
    packages:
    - ghostscript
env:
  global:
  - secure: ! uru4Ga12MPDtRCizuNQXh8LMWJXpclf+unYV235/hEAiiEaubOy8AnHKIPHqV45FEqu0ASJaN2LxcxCydh1MLyn+ECjRE1ZzwUk8qZiEJkRPeNOEXJ4VaWO7Epd1+9j53883P0Xp/zjLfeY9FzR1Ews2iGmaw7lMujXnzJhWgaG6QO7D41oZVXYHMqBi6kV2MzxBReIDzEOAvc6lN+vS8WRKMmILaQFAtlK+vg99U/faOMYfHqH8LTYM7sJ5V8jgSI730PMN6CD7kGiWR3Vi8kc4sV/U8rS9TgpVmYN4RzBZ8OfxxOobXMmVmuD8Lrfu2pCa/c5O3EKVC8DzSb9etwjoDGQpC1lZ29pmJRtTb6QFZnwE8S2W3r7buk2/mRPsVPEyj2qqJEhEwYX7Zqg7rEF/tyKIBTqTOXPeznK8cV729gE7EJjFrhgPAhan6kJdpASY6meYOsIQ3WLS5j8888tX6XvzEAg1R3x2+tCgD+cUoc8UBGJWy2m4+KHorab5duYYv+UFZzh1MPc41Y0HYnUvmGYo1szQVNG+c1f7ECTe+p7TWsmhcUKIiTRqfWIfK4vjGLMczwfEhUOsBW1seL1wcJmjvEP8AxA3vdk5/5qVlH5DAUMH/xCNA7nxnjD7CkTiTRRgkJx6hx1uk8jwOvyU+WG9XPVDB2TZXj1fVcM=
  - secure: ! ZhSmhEOMmSQZlxL+aWG9pVRHw6H453H5Wpb9nJeDSO1TUkwhJuvCqRAWdHEIDodNJEibt1woCh7M3kMtYLrc7tQoYFwYl/PP/fvm+Go1vdeyx/wnR8Vn9RkjaBg/Z7sPVbMDdK26w8M/pApQ5CewmpA0yeQ6ElP9HpSXcc795W3iOGzOZL8XvH0UOPIWDottMB4lakCmMT2QT75rv0UKTQF+vriNn4jEPRqLw7Rtd8chgJkLNqI5L7yQUjPMbf6OCgrhig7gKLW8tTxS287jMH2eVfLNWywnKKiZc/xty5INq9ngWplZ+BmSQ9PvqXMzGV6DEUg/y3xWf/cenKXXuQf85rcjLSV7cRy1QlO5blAzZHl00M40vH5z9/e4l0fe0ShfIyaVrpVzkroT6kRXNXeWH1A7cQ2kZDNYYxFqDNyyjGxl7WsvGe3dH1eu+XQ7aBaLXjH5re+upC8YZ5XTu32h6qoZ0VSKuk+/Q7sXfxs9rI0Ve+SseAFkjsxg7++nmmrwoyWovXlc4AcE32R5KzkTWnxgAdRHfh6ZcYczmn1cH0jp4CKCjQCEApwD/HXLkAKWvdp7pUs+Hsdl5+tNqfTrJpT4s8+1n9SwMFUekUUsSpLfgGt7/APl+qgY5IQM0rLqlkn+/cxdFgQ3lwrxTU6WmvfoedxQoOZ4C9J3bX0=
  - secure: ! ASYdey8UiBR+OLR1SXQh+/Y9Q3pRNzOvmAeqPca9HAbEaNKVW0/DcBf4xnIHoomjXqZ2aZH+Ah6vaQ2g58xCujkP4C3tHB+E8ywzqfFbDIug21KgoMJK/aqdmOMVvJIqb1grnFuBTaYfNnTufg58QonlUN66nR+qbgU8nc0SttMdzLtF+L/TLasrrdxr8K/EesNRFdWXgrblJ/TCJNiMn9LkocF0kTkdZ1Uokh9prpiFAXbu1KnqTCYNmVc4jkHQWu7aXuvPENO61I8a3u3OQ+s3VfTV5u54VpdIhpxFNlzM8w4oBthilyavWs3aAI5aqSNwg3D39s8QDaCkPWxRlL7nBl0ecaMIKAgDn2fZYKlRLQxxepb/Qq0sBOTCzXEaWF/GfVxbsZqaEms6md0ReeMJutLNmJdg0NzlHSarZ4SrOz9uc3Lw/UP9fAMrxwtFUiljNaWPxpQxdQiSClpqWovXDa2M3zOx+Ps3moDRFL0gV9QMZLlSfiWO4xLiWwXOd8pBWC6iWLgoqkRy9eLVB1XHXJ8ci8RA7RAB+zMP9T3StBq+EjkG1CBTdzcj1O63GS6lTkcjXbynX4YtTxX61Cyu04Wrq8mF/t32kK2Azf3kiTJv1z2F20EndJrHdHh0YqtcM43Pg4YRThF7UZ9/knb+pnm/UJrrKHcBN7z9HPk=
  - secure: ! rLPcNn3y534jIopnxM8611ONZ0DYt8rHu/QbM5CoxVav6vdoufoVD+deal0nNT7SskQd5fTIF2RBEhpLFWYuBxTSTt1FRr/Iqug5hSpP2wBs3mTXXpCD64s1QkG9NaJ+9wBLpWveATMpZhQeljhK4u+xqTWcSly8eReOIT9xA/q8rFy1ctCiW4KTeLX0zangpDwEiJx4oBjGY58i5Cp+k5w7VQ+b7icKK/AqVbCW+GTTXq8q2a1DunvHcpZH9FNcDu+eAy/wN1C5LOop/myH4ZtE3Qe/q3QjQmw+yi1EJtuIhtwZLqUvv1ROOuGeuER6VGZkx+Fmx8oxH3YXr6fOSime47fMFBPu53qVb7Tq/l1mPqOSMQK1u8Wa1Ud7kQrTCnnsFAhgYlwGrVlYqqOhSu+rikbfM4w0Sqb3Xra2PfbwdhHuSvYyrHC1pZx8c/VqTY0Y6ER0FVldBl2pnjW0fkOMKPDPe1Yk8tmB1k7GIFgiEhc57IxP9GKROlDjIaNlc2wfDjUp/3kXhX4fYJkXRnIDSrCU8Wf/JV3oHiifC1erzuKWWdMVbnIz4Jn0HhMQCUQGruS1jDg7H8GVOqQxnaj1HsTDLzHyguwoyio/M1WG1buNRWPKlkbhCXQJ9T8o/7B57mE41sBhUb6GGr/cgYXsCpYEbPHVVHgrSd3uhg0=
  - secure: ! Rt+GYRTbpJjDiL+RGdorgGFm4xlueph3lMqBoJ+jwhMlZciBptnlzkDUwHEV9jFyBraUWvC+peUvZ2mAyy5lABnbf3iq9BA4B49tc2SUuS5r7pLt3YbPEwu4/n+7GFougteh6ukcenXxrk4eic8BIv0F163iWNXQbnL07ooPZpahP7704OdapiugASyQNpmQH0A6f9ss/L5vk0EFOoEx3oIRFfm+c6RALt4vgtdjDIDAXY+27wS+G5EOFqFkgKoPPVsGXMdnWjS4J8TrZ2qN9buXu8nTp7b6ApoxtG3kEO5eNPHH5uPujLPb3MfN1JgrGTDZzNnUz0YzK6UrItoMeSomOgNTcbQojmG783b53Uzv1HIrx6hSgAcgb7iZfTzHVd3250zcdHjy8O2NxTDQ5NmJzChdWX5gVcVJT6K+6YV80TsPdst5PQnN5umDWBf3UQyIcG2hq9xK3zh3aNwZyRgLFYTYG9uhCyyZ03xX57pxlLZvsVmybiacuxVcno+1G/GbP8C4vFT/Hv0/D1WMzr3ascYozxir0wU+pOZtsmyoM3J6AvRl5CfocSM+ZdjrIffx75K8ZwHQVNqGjzN6Xz9xAGC10H2FNPJkzmzDB2CalK4kL4aV76+heIa+jiMjTR/YvgGUtmKzHBi+iGs1L3/8TAkWsX4uNe+CyIUZCuY=
  - secure: ! WEkd12ZUADBucUluM4sh0M988GMt0bAwNhpAIGyYI0wDWoHaPXESwngGXvK639VIMRrd7UJPPIwAFxfkuB4vRyWeocE9f+8yxItiuSR0IXD6fhhmJxzJGJ3oSist4bhl2llUYMh4vRVsUicKSIUDgWpkYyagCqG7PAyNCCEt/Govir15SPD0bei952idatpSLaKvxGZixLU56kNDNRJ0wodMPildmOY7yVcP+0utQ+Fn2QZ/cXZ7epXN9OsEyzIl8yo5w0jAU6pMXYvqnkm/tkRxq/GBOkRpfqpghn38wsJ8/8koKF3aNgP7HW6Rj9CvulkhG+7M+Kv/b3JwNYTgwX9OY0aqRg6rUjNduoQ6RSC7ebn8TkzGrHyTuXmCk3eGqUc5JOFVFVymmnOMNuxMuprK1NiiPoD+xIcW2rnS2+JkRfhfU29m+CKEyg43MgOQrfsXzGhfjvZWEdlgH92ZBEMn8YsjJAG4/ap+w4/rAl9OFrMyVvyKVnFxrlfb8mqOX8ipr4smtvZyKNNYqoJ2HFFlyKbtjOF1DS7XVdTzDDG/FBSv2095X/Vp08+DQnVWQ2irkZV4w3onJ7mnTrprAY8DDvORkUkKgfORWdmYUe4tBhEbzR/EN+9pIJ9zi8z4bWLZnvNxEiSSI92a6tkHIncW0c08CO3IfIQ5AqaqyiA=
before_install:
- redis-server --version
- sudo mount -o remount,size=25% /var/ramfs
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda3/bin:$PATH
- conda update --yes conda
install:
- travis_retry conda create --yes -n labadmin python=2.7 pip
- source activate labadmin
- pip install -U pip
- pip install -U click natsort coverage coveralls
- travis_retry pip install -U .[test]
script:
- git clone https://github.com/biocore/american-gut-web.git ~/build/biocore/american-gut-web
- cd /home/travis/build/biocore/american-gut-web
- export AG_CONFIG=`pwd`/ag_config.txt.example
- export PYTHONPATH=/home/travis/build/biocore/american-gut-web:$PYTHONPATH
- set | grep -i testing
- "./scripts/ag make test"
- 
- cd $TRAVIS_BUILD_DIR
- cp $TRAVIS_BUILD_DIR/knimin/config.txt.example $TRAVIS_BUILD_DIR/knimin/config.txt
- nosetests --verbose --with-doctest --with-coverage --cover-package=knimin
- flake8 --ignore E722 knimin setup.py scripts
after_success:
- coveralls
- echo "foo"
