dist: trusty
language: python
python:
- '2.7'
sudo: false
services:
- redis-server
addons:
  postgresql: '9.5'
  apt:
    packages:
    - ghostscript
env:
  global:
  - secure: uru4Ga12MPDtRCizuNQXh8LMWJXpclf+unYV235/hEAiiEaubOy8AnHKIPHqV45FEqu0ASJaN2LxcxCydh1MLyn+ECjRE1ZzwUk8qZiEJkRPeNOEXJ4VaWO7Epd1+9j53883P0Xp/zjLfeY9FzR1Ews2iGmaw7lMujXnzJhWgaG6QO7D41oZVXYHMqBi6kV2MzxBReIDzEOAvc6lN+vS8WRKMmILaQFAtlK+vg99U/faOMYfHqH8LTYM7sJ5V8jgSI730PMN6CD7kGiWR3Vi8kc4sV/U8rS9TgpVmYN4RzBZ8OfxxOobXMmVmuD8Lrfu2pCa/c5O3EKVC8DzSb9etwjoDGQpC1lZ29pmJRtTb6QFZnwE8S2W3r7buk2/mRPsVPEyj2qqJEhEwYX7Zqg7rEF/tyKIBTqTOXPeznK8cV729gE7EJjFrhgPAhan6kJdpASY6meYOsIQ3WLS5j8888tX6XvzEAg1R3x2+tCgD+cUoc8UBGJWy2m4+KHorab5duYYv+UFZzh1MPc41Y0HYnUvmGYo1szQVNG+c1f7ECTe+p7TWsmhcUKIiTRqfWIfK4vjGLMczwfEhUOsBW1seL1wcJmjvEP8AxA3vdk5/5qVlH5DAUMH/xCNA7nxnjD7CkTiTRRgkJx6hx1uk8jwOvyU+WG9XPVDB2TZXj1fVcM=
  - secure: ZhSmhEOMmSQZlxL+aWG9pVRHw6H453H5Wpb9nJeDSO1TUkwhJuvCqRAWdHEIDodNJEibt1woCh7M3kMtYLrc7tQoYFwYl/PP/fvm+Go1vdeyx/wnR8Vn9RkjaBg/Z7sPVbMDdK26w8M/pApQ5CewmpA0yeQ6ElP9HpSXcc795W3iOGzOZL8XvH0UOPIWDottMB4lakCmMT2QT75rv0UKTQF+vriNn4jEPRqLw7Rtd8chgJkLNqI5L7yQUjPMbf6OCgrhig7gKLW8tTxS287jMH2eVfLNWywnKKiZc/xty5INq9ngWplZ+BmSQ9PvqXMzGV6DEUg/y3xWf/cenKXXuQf85rcjLSV7cRy1QlO5blAzZHl00M40vH5z9/e4l0fe0ShfIyaVrpVzkroT6kRXNXeWH1A7cQ2kZDNYYxFqDNyyjGxl7WsvGe3dH1eu+XQ7aBaLXjH5re+upC8YZ5XTu32h6qoZ0VSKuk+/Q7sXfxs9rI0Ve+SseAFkjsxg7++nmmrwoyWovXlc4AcE32R5KzkTWnxgAdRHfh6ZcYczmn1cH0jp4CKCjQCEApwD/HXLkAKWvdp7pUs+Hsdl5+tNqfTrJpT4s8+1n9SwMFUekUUsSpLfgGt7/APl+qgY5IQM0rLqlkn+/cxdFgQ3lwrxTU6WmvfoedxQoOZ4C9J3bX0=
before_install:
- redis-server --version
- sudo mount -o remount,size=25% /var/ramfs
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda3/bin:$PATH
- conda update --yes conda
install:
- travis_retry conda create --yes -n labadmin python=2.7 pip
- source activate labadmin
- pip install -U pip
- pip install -U click natsort coverage coveralls
- travis_retry pip install -U .[test]
script:
- git clone https://github.com/biocore/american-gut-web.git ~/build/biocore/american-gut-web
- cd /home/travis/build/biocore/american-gut-web
- export AG_CONFIG=`pwd`/ag_config.txt.example
- export PYTHONPATH=/home/travis/build/biocore/american-gut-web:$PYTHONPATH
- set | grep -i testing
- "./scripts/ag make test"
- 
- cd $TRAVIS_BUILD_DIR
- cp $TRAVIS_BUILD_DIR/knimin/config.txt.example $TRAVIS_BUILD_DIR/knimin/config.txt
- nosetests --verbose --with-doctest --with-coverage --cover-package=knimin
- flake8 --ignore E722 knimin setup.py scripts
after_success:
- coveralls
- echo "foo"
